perl5-dbi/DBD-Oracle

lib/DBD/Oracle.pm
Some documentation was "strongly inspired" by DBD::Pg documentation. So strongly, that we forgot to change 'Pg'
to 'Oracle' in a few places. :-)
Caught by Martin J. Evans.
=> Change DBD::Pg to DBD::Oracle

oci8.c, ocitrace.h
The commits here fix errors in format strings that I noticed when @abraxxa reported test failures in t/38taf.t under Perl 5.22.1-RC4.
I don't have Oracle to run tests against, so **please do not apply this patch untested**. However, I'm fairly sure that the current code is incorrect; and these changes, although not even compiled, seem likely to fix the problems I could see in @abraxxa's reported compiler output.
Thanks.
=> Fix printf format-string errors on 64-bit Linux

oci8.c
presently selecting from CLOB, BLOB, or LONG columns using the ora_piece_lob option will produce empty strings rather than undefs for null values in oracle. this fix makes it behave the same as the other lob select modes
=> Set zero-length lob to undef when using ora_piece_lob option

Makefile.PL
and the build is for 64 bit.
This is the location of 64 bit library files when Oracle Instant Client 12+ is installed from a package on Solaris 11+.
Yes, I know that adding $ORACLE_HOME/lib/64 to LD_LIBRARY_PATH will fix issues with compiling. But when you build with LD_LIBRARY_PATH set you are always forced to set it in your environment from there on out. This simple additional check allows you to compile without LD_LIBRARY_PATH set (on SunOS).
=> Have ora_libdir check $ORACLE_HOME/lib/64 when it exists

Makefile.PL
Though DBD::Oracle no longer supports versions older than 9.2, the default client version we were setting was 8.0.0.0. Bumped this to be a more reasonable 9.2.0.4.0 which will allow DBD::Oracle to build on systems where it cannot determine the client version.
=> Fix for Oracle version default value.

dbdimp.c
should fix #35 
I haven't been able to test this beyond compiling it.
=> correct the type passed to OCIAttrGet() for OCI_ATTR_TAF_ENABLED

Makefile.PL
These additional checks makes it to where if you installed Instant Client from the RPMs (basic and devel), then Makefile.PL will pick it and the correct (and highest if there are multiple) version without ORACLE_HOME being set. Setting ORACLE_HOME or LD_LIBRARY_PATH will grab the version from the path.
This patch is probably best paired with DBI 1.623 requirement since DBI 1.623+ allows for LD_LIBRARY_PATH to not be set at all.
This is a redo of pull request #71.
This resolves issue #68.
=> Improve finding ORACLE_HOME when installing on Linux OS

.travis.yml, dbdimp.c
**This pull request is for testing only - please don't merge** 
As the order of object destruction during "global destruction" is
undefined. DBI traces show that the global environment is freed in the
driver destruction process before all database connections are closed
and their resources freed. This causes the segfault in #65.
This change moved freeing of the global environment handle from the
destruction of the driver handle (dbd_dr_destroy()) to the destruction
of the database handle (dbd_db_destroy()).
This implementation closes the global environment handle during the DBI
shutdown process if the last database handle uses the global
environment handle.
If the last database handles uses a session environment handle, the
global environment handle will not be destroyed.
=> Move freeing global envhp to destruction of last dbh

.travis.yml, README, dist.ini, lib/DBD/Oracle.pm, maint/Dockerfile, maint/docker-init.sh, maint/travis-ci_scripts/01_install_oracle_xe.bash
tweaking pod and dist.ini
adding a Dockerfile to help people hack on this code quickly to help with #111
=> non-functional changes

Makefile.PL
Fixes issue #128 on macOS by adding `rpath` to the directory given in `ORACLE_HOME` to `DBD/Oracle/Oracle.bundle`.
I observed the following output on my machine: 
```
$ otool -L libclntsh.dylib
libclntsh.dylib:
@rpath/libclntsh.dylib.19.1 (compatibility version 0.0.0, current version 0.0.0)
@rpath/libnnz19.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
@rpath/libclntshcore.dylib.19.1 (compatibility version 0.0.0, current version 0.0.0)
```
Notice the `@rpath` install name. So I figured the perl bundle in `DBD/Oracle/Oracle.bundle` needed an rpath to the `ORACLE_HOME`.
Note that with this change, I do not need to set …
=> Add rpath to ORACLE_HOME to DBD/Oracle/Oracle.bundle

Makefile.PL
Patch based on a proposed fix by Slaven Rezić <eserte> in https://github.com/perl5-dbi/DBD-Oracle/issues/72 and improved by me afterwards.
The patch has been successfully applied to Debian for a few releases now:
https://salsa.debian.org/perl-team/modules/packages/libdbd-oracle-perl/blob/master/debian/patches/build-without-ld-libray-path.patch
Closes: #72
=> Build DBD::Oracle on Debian systems without LD_LIBRARY_PATH

t/25plsql.t
non-assigned bug. These versions will be skipped in 25plsql.t.
Originally reported in GH#70.
This is still a problem in 19.9 and 19.13 so we should skip testing those too. I also got with @cjbj on the status of Oracle Bug 22813401 and he says the status hasn't changed.
=> Updated list of OCI versions known to have bind_param_inout

Makefile.PL
major version number.
The following has always been supported (note the /lib):
ORACLE_HOME=/usr/lib/oracle/21/client64/lib
As of Instant Client 21 this will fail with "can't find the header files" since find_headers() does not account for major version number only in the path. This was somewhat talked about/fixed in GH#127.
The above isn't however an issue if you leave /lib out of the ORACLE_HOME. But like I said it was never an issue before 21.
The fix is to have find_headers() also look for paths with the major number only. This helps the search for headers in general.
It also fixes not setting ORACLE_HOME at all (which is also supported if LD_LIBARY_PATH is set).
=> Have find_headers() also search for header files based off the

Makefile.PL
Header file dbivport.h should be installed as well per the DBI instructions in dbivport.h itself.
Not sure why it hasn't been getting installed all along since a local copy of dbivport.h has been part of DBD::Oracle distro for a long time.
This fixes #159.
=> dbivport.h should be installed

dbdcnx.c
The transformation of inline function llist_drop to macro llist_drop introduced a bug: the return statement was meant to leave to inline function, but after the transformation it leaves the function that calls the macro.
Also if your compiler is strict enough, it won't compile, as the macro is called from both 'void' and 'non-void' functions.
The fix is changing the code, from if (cond) return; rest; to if (!cond) { rest; }
=> Changing 'return' to block statement, fixing a problem created while transforming inline function to macro

Makefile.PL
On Gentoo, for better or worse, we install oracle-instantclient on 64-bit systems to /usr/lib64/oracle/client/ with:
* /usr/lib64/oracle/client/lib for 32-bit libraries (multilib)
* /usr/lib64/oracle/client/lib64 for native 64-bit libraries
Adapt the logic to handle lib64 if it exists and we're using a 64-bit Perl.
(And fix some whitespace while at it.)
=> Makefile.PL: help ora_libdir find ORACLE_HOME on Gentoo

Makefile.PL
On Gentoo we install oracle-instantclient libraries in /usr/lib64/oracle/client/lib64 on 64-bit systems and in /usr/lib/oracle/client/lib on 32-bit systems.
This was done because in a 64-bit system with multilib, both 32-bit libraries (/usr/lib64/oracle/client/lib) and 64-bit libraries (/usr/lib64/oracle/client/lib64) were installed. For now, this specification is disabled because it is rare to have the same version of oracle instantclient for both 32-bit and 64-bit.
=> Makefile.PL: help to find linking libraries on Gentoo

.github/workflows/action.yml, Makefile.PL
I added Test::NoWarnings but it still wasn't installing the module. Turns out there was an ancient condition that modified PREREQ_PM. I removed this since it will probably never be true for anybody again. Updated GHA accordingly.
This fixes #175.
=> Makefile.PL fix for missing Test::NoWarnings build requirement

dbdimp.c, oci8.c
As the minimum required version of DBI is 1.623, these
when the versions stored in these variables change in DBI
=> Remove outdated #ifdefs

t/90-segv-threads.t, t/91-segv-fork.t, t/92-segv-fork.pl, t/92-segv-fork.t
I have fixed all DBD::Oracle bugs (I could detect). I have this remaining
SEGV fault within Perl itself.
ADDED: Additional forking test that reproduces SEGV
within Perl 5.30.3+ using Oracle 19, 21 & 23. I've only tested
with these combinations.
```
$ gdb $(which perl)
-- snip --
(gdb) run t/92-segv-fork.t
-- snip --
Thread 2 "perl" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1cc4680 (LWP 9807)]
0x000055555562e610 in Perl_csighandler3 (sig=17, sip=0x0, uap=0x0) at mg.c:1601
1601	           (PL_signals & PERL_SIGNALS_UNSAFE_FLAG))
(gdb) list
1596	           sig == SIGSEGV ||
1597	#endif
1598	#ifdef SIGFPE
1599	           sig == SIGFPE ||
1600	#endif
1601	           (PL_signals & PERL_SIGNALS_UNSAFE_FLAG))
1602	        /* Call the perl level handler now--
1603 …
```
=> Test cleanups & New SEGV forking test reproduction
